---
apiVersion: v2
name: wayfinder
description: >
  A Helm chart for installing Voyages (a collection of Helm Charts
  and pre-tested configs to yer cluster).
type: application
version: 0.1.1
appVersion: 0.1.1

dependencies:
  - name: external-secrets
    alias: externalSecrets
    version: 0.9.10
    repository: https://charts.external-secrets.io
    condition: render-subcharts
  - name: komodor-agent
    alias: komodorAgent
    version: 2.1.0
    repository: https://helm-charts.komodor.io
    condition: render-subcharts
