apiVersion: v2
name: wayfinder
description: A Helm chart for installing Voyages -  A named collection of Helm Charts and pre-tested configureations to a Kubernetes cluster.

type: application

version: 0.1.0

appVersion: "0.1.0"

dependencies:
  - name: kube-prometheus-stack
    version: 54.0.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: render-subcharts
  - name: cert-manager
    version: 1.9.1
    repository: https://charts.jetstack.io
    condition: render-subcharts
  - name: external-secrets
    version: 0.9.10
    repository: https://charts.external-secrets.io
    condition: render-subcharts
