---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/fluxcd/flux2-monitoring-example
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: ./monitoring/configs
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flux-source
  namespace: flux-system
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "self-signed"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - source.flux.local
      secretName: source-ingress-tls
  rules:
    - host: source.flux.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: source-controller
                port:
                  number: 80
