---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flux-pvc
  namespace: flux-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
